### ISSUE TITLE
Script is not executed using Python

### ISSUE THREAD

**Issue by remidefleurian** [Jorl17/sharelatex-git-integration-unofficial#3]
Hi there! I followed the very clear instructions to install the script, and everything worked perfectly, except that using the command `sharelatex-git` seemed to open the script with a different interpreter than Python.

For instance, `sharelatex-git - h` did not work, but `python sharelatex-git.py -h` worked perfectly. I managed to solve the issue by swapping the first two lines of the Python script, therefore making sure that `#!/usr/bin/env python3` was the first line in the code.

Just thought I'd share this. Let me know if you'd like any more details!

**Comment by Jorl17** [comment]
Fixed by https://github.com/Jorl17/sharelatex-git-integration-unofficial/commit/51398dcd98a784af3e212f6222bac2682759b37d, I believe :)
